apiVersion: v1
kind: Pod
metadata:
  name: dragonfly
  labels:
    app: dragonfly
spec:
  containers:
    - name: dragonfly
      image: docker.dragonflydb.io/dragonflydb/dragonfly
      args: ["--port", "6379"]
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly
spec:
  selector:
    app: dragonfly
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31379
